name: lint
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  Linter_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install_PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Make_Install
        run: make install
      - name: Make_Lint
        run: make lint
